### ISSUE TITLE
Update scope

### ISSUE THREAD

**Issue by cshold** [cshold/jQuery-Facebook-Photo-Selector#19]
Receive this error as the developer when trying to login:

> Invalid Scopes: friends_photos. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Anyone up for contributing?

**Comment by etienneo** [comment]
Hello,
First thank you for this project, it is really helpful!
I think the error is due to something wrong with your API key for the demo, maybe it has not been updated for the v2.4? Because using your API key I get:
CS Photo Selector will receive the following info: your public profile.
When I get this using my API key with the exact same code
*** will receive the following info: your public profile and photos.

Also, the friends_photos permission's scope is [not available anymore since the v2.0 of the API](http://stackoverflow.com/questions/23614537/what-facebook-permissions-are-required-to-view-photos-that-your-friends-are-tagg).
